const Profiles = require('../models/models');
const mongoose = require('mongoose');

const names = [
  'James',
  'Robert',
  'John',
  'Michael',
  'David',
  'William',
  'Richard',
  'Joseph',
  'Thomas',
  'Christopher',
  'Charles',
  'Daniel',
  'Matthew',
  'Anthony',
  'Mark',
  'Donald',
  'Steven',
  'Andrew',
  'Paul',
  'Joshua',
  'Kenneth',
  'Kevin',
  'Brian',
  'Mary',
  'Patricia',
  'Jennifer',
  'Linda',
  'Elizabeth',
  'Barbara',
  'Susan',
  'Jessica',
  'Sarah',
  'Karen',
  'Lisa',
  'Nancy',
  'Betty',
  'Sandra',
  'Margaret',
  'Ashley',
  'Kimberly',
  'Emily',
  'Donna',
  'Michelle',
  'Carol',
  'Amanda',
  'Melissa',
]

const locations = [
  'Belmont',
  'Berkeley',
  'Beverly Hills',
  'Brea',
  'Buena Park',
  'Burbank',
  'Calexico',
  'Calistoga',
  'Carlsbad',
  'Carmel',
  'Chico',
  'Chula Vista',
  'Claremont',
  'Compton',
  'Concord',
  'Corona',
  'Coronado',
  'Costa Mesa',
  'Culver City',
  'Daly City',
  'Davis',
  'Downey',
  'El Centro',
  'El Cerrito',
  'El Monte',
  'Escondido',
  'Eureka',
  'Fairfield',
  'Fontana',
  'Fremont',
  'Fresno',
  'Fullerton',
  'Garden Grove',
  'Glendale',
  'Hayward',
  'Hollywood',
  'Huntington Beach',
  'Indio',
  'Inglewood',
  'Irvine',
  'La Habra',
  'Laguna Beach',
  'Lancaster',
  'Livermore',
  'Lodi',
  'Lompoc'
]

createTestUsers = async (i) => {
  const data = await Profiles.create({
    name: names[i],
    username: names[i],
    password: `password_${i}`,
    profilePicture: 'none',
    sex: i % 2 === 0 ? 'M' : 'F',
    height: 60 + i,
    weight: 150 + i * 10,
    age: 20 + i,
    fightingStyle: i % 2 === 0 ? 'SouthPaw' : 'Orthodox',
    totalWins: i,
    totalLosses: 48-i,
    location: locations[i],
  })
}

for (let i = 0; i < 46; i++) {
  createTestUsers(i);
}
